### PR TITLE
feat: allow tabs lazy loading

### LINKED ISSUE #431: ionic 4 lazy load
hi! is there a way to implement lazy load feature in ionic 4? i'd already tried but all of my tab component got load

### PR DESCRIPTION
**Pull request by ihadeed**
closes #431

### CODE REVIEW

**Comment by darron1217** [comment]
Awesome!
But I wonder why this feature not merged yet?

**Comment by ihadeed** [comment]
> Awesome!
> But I wonder why this feature not merged yet

I haven't had the time to test it yet

It should work as expected, mainly looking to test performance and user experience.

**Comment by heerenjasper** [comment]
When will this be merged?

**Comment by alexanderbelokon-mway** [comment]
How can this project be build from the feature branch for an Angular project?

**Comment by Karabillie** [comment]
we fixed it at the pull request [](https://github.com/zyra/ionic-super-tabs/pull/464)

**Pull request merged**
