### PR TITLE
Add avoid-super-tabs attribute

### PR DESCRIPTION
**Pull request by stionic**
Hi @ihadeed ,

I have added avoid-super-tabs attribute for avoid swipe event, hope it will helpful.

Regards.

### CODE REVIEW

**Comment by sfaizanh** [comment]
@stionic have you tested on real device?

**Comment by stionic** [comment]
Hi @sfaizanh

Yes, tested in Android and iOS, work fine.

Regards.

**Comment by sfaizanh** [comment]
Awesome

**Comment by ihadeed** [comment]
Thanks for the PR @stionic 

Could you please provide an code sample to see how this would be used?

**Comment by stionic** [comment]
@ihadeed i

Hi,
Current, if inner super-tab component has ion-scroll horizontal then it will not work because when swipe will change tab instead of scroll.
With this pull request, developers can add avoid-super-tabs attribute for avoid swipe event and can scroll horizontal.

Sample:
```
<ion-scroll scrollX="true" avoid-super-tabs="true">
   <!-- Scroll content -->
</ion-scroll>
```

Regards.

**Comment by ihadeed** [comment]
Great thanks! this is awesome.

**Comment by srjovanovic** [comment]
Is this attribute implemented in 4.2.2 npm package?

**Comment by stionic** [comment]
@srjovanovic 

Hi, lastest version 4.2.2 in NPM package published 5 months ago.
Now you can install this repo by:

> npm install https://github.com/zyra/ionic2-super-tabs.git

**Comment by srjovanovic** [comment]
@stionic 
Thanks

**Comment by spyman143** [comment]
how do i install super-tabs with avoid-super-tabs="true" attribute.? I tried with 
npm i --save ionic2-super-tabs but avoid-super-tabs not working.

**Comment by stionic** [comment]
@spyman143 

Please try:

> npm install https://github.com/zyra/ionic2-super-tabs.git

Regards.

**Comment by spyman143** [comment]
i had install with above link, but its removed my supertabs inner folder such as dist from node_modules.

**Comment by stionic** [comment]
Hi,

I have tried `npm install from github` but not luck,
Best way is wait for @ihadeed ihadeed release new version.

**Comment by stionic** [comment]
@spyman143 

Hi,

Version 4.3.0 released 8 days ago have added this pull request.
You can update now:

`npm uninstall ionic2-super-tabs`
`npm install ionic2-super-tabs`

Regards.

**Pull request merged**
